# 示例配置文件
app:
  Name: "scheduler for ZSC Network Support staff"
  ListenPath: ":25005"
  MemberFile: "member.csv"
  FrontEndDir: ""
  TemplateDir: ""
option:
  DatabaseAutoMigrate: false
  Debug: true
DB: # 数据库的其他信息要通过环境变量传递。
  Type: "SQLite"
business:
  Year: "2024-2025"
  Semester: 1
  StartTime: "2025-3-10"
  Week: 15
